CREATE DATABASE concours_photo

CREATE TABLE user (
id INT PRIMARY KEY AUTO_INCREMENT, 
nom VARCHAR (30) NOT NULL,
prenom VARCHAR (30) NOT NULL,
departement VARCHAR (30) NOT NULL,
);

CREATE TABLE photo (
id INT PRIMARY KEY AUTO_INCREMENT,
legende VARCHAR (200) NOT NULL,
FOREIGN KEY(user_id1) REFERENCES user(id)
);


CREATE TABLE vote(
id INT PRIMARY KEY AUTO_INCREMENT,
FOREIGN KEY(user_id2) REFERENCES user(id)
FOREIGN KEY(photo_id) REFERENCES photo(id)
);
